INSERT INTO ocupaciones(idOcupaciones, ocupacion) VALUES (1,'desocupado');
INSERT INTO ocupaciones(idOcupaciones, ocupacion) VALUES (2,'inactivo');
INSERT INTO ocupaciones(idOcupaciones, ocupacion) VALUES (3,'asalariado privado');
INSERT INTO ocupaciones(idOcupaciones, ocupacion) VALUES (4,'asalariado publico');
INSERT INTO ocupaciones(idOcupaciones, ocupacion) VALUES (5,'miembro de cooperativa de produccion');
INSERT INTO ocupaciones(idOcupaciones, ocupacion) VALUES (6,'patron');
INSERT INTO ocupaciones(idOcupaciones, ocupacion) VALUES (7,'cuenta propia sin local o inversion');
INSERT INTO ocupaciones(idOcupaciones, ocupacion) VALUES (8,'cuenta propia con local o inversion');
INSERT INTO ocupaciones(idOcupaciones, ocupacion) VALUES (9,'programa publico (social) de empleo');
INSERT INTO ocupaciones(idOcupaciones, ocupacion) VALUES (10,'miembro del hogar no remunerado');
