INSERT INTO ECH_DW.tics(idTics, celular, usoInternet) VALUES (1,0,'Al menos una vez al dia');
INSERT INTO ECH_DW.tics(idTics, celular, usoInternet) VALUES (2,0,'Al menos una vez a la semana, pero no todos los dias');
INSERT INTO ECH_DW.tics(idTics, celular, usoInternet) VALUES (3,0,'Al menos una vez al mes, pero no todas las semanas');
INSERT INTO ECH_DW.tics(idTics, celular, usoInternet) VALUES (4,0,'No sabe');
INSERT INTO ECH_DW.tics(idTics, celular, usoInternet) VALUES (5,0,'No usa');
INSERT INTO ECH_DW.tics(idTics, celular, usoInternet) VALUES (6,1,'Al menos una vez al dia');
INSERT INTO ECH_DW.tics(idTics, celular, usoInternet) VALUES (7,1,'Al menos una vez a la semana, pero no todos los dias');
INSERT INTO ECH_DW.tics(idTics, celular, usoInternet) VALUES (8,1,'Al menos una vez al mes, pero no todas las semanas');
INSERT INTO ECH_DW.tics(idTics, celular, usoInternet) VALUES (9,1,'No sabe');
INSERT INTO ECH_DW.tics(idTics, celular, usoInternet) VALUES (10,1,'No usa');
