INSERT INTO ECH_DW.edades(idEdades, edad) VALUES (1,'0 a 14');
INSERT INTO ECH_DW.edades(idEdades, edad) VALUES (2,'14 a 18');
INSERT INTO ECH_DW.edades(idEdades, edad) VALUES (3,'18 a 22');
INSERT INTO ECH_DW.edades(idEdades, edad) VALUES (4,'22 a 30');
INSERT INTO ECH_DW.edades(idEdades, edad) VALUES (5,'30 a 40');
INSERT INTO ECH_DW.edades(idEdades, edad) VALUES (6,'40 a 50');
INSERT INTO ECH_DW.edades(idEdades, edad) VALUES (7,'50 a 60');
INSERT INTO ECH_DW.edades(idEdades, edad) VALUES (9,'60 a 70');
INSERT INTO ECH_DW.edades(idEdades, edad) VALUES (10,'mas de 70');
